### ISSUE TITLE
svgo Error: ../svgo.js:3 const getStdin = require('get-stdin');

### ISSUE THREAD

**Issue by martenzander** [1000ch/Sublime-svgo#1]
Hi, I just installed your plugin and when and when trying to minify my svg, I get the following error:

> svgo
> Error: /Users/marten/Library/Application Support/Sublime Text 3/Packages/SVGO/svgo.js:3
> const getStdin = require('get-stdin');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

Am I doing something wrong? I do have node 6.9.1 installed.

**Comment by 1000ch** [comment]
Please use the newest package and Node.js.
