### ISSUE TITLE
TypeError: options.plugins is not iterable

### ISSUE THREAD

**Issue by davidwebca** [1000ch/Sublime-svgo#3]
Hi! First, thanks a lot for that plugin. I use it all the time!

Since the last update though, I have this : 

```
svgo
Error: ~/Library/Application Support/Sublime Text 3/Packages/SVGO/svgo.js:21
  for (const plugin of options.plugins) {
                               ^

TypeError: options.plugins is not iterable
    at minify (~/Library/Application Support/Sublime Text 3/Packages/SVGO/svgo.js:21:32)
    at ~/Library/Application Support/Sublime Text 3/Packages/SVGO/svgo.js:7:17
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

Is there anything I can do on my end to fix it?

**Comment by paulmist** [comment]
Same issue. Here's my error:

```
TypeError: options.plugins is not iterable
at minify (~/Library/Application Support/Sublime Text 3/Packages/SVGO/svgo.js:21:32)
at ~/Library/Application Support/Sublime Text 3/Packages/SVGO/svgo.js:7:17
at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by hunterruth** [comment]
Same issue for me. :(

**Comment by davidwebca** [comment]
I really needed this to work for a current project I'm working on and to make sure I would not lose any time so I found the issue.

Alright for those who would like to hotfix the plugin, you can revert the change in 7236076e0714c81877b5b5ed990e3b491458e744

Change both loops back to "for in" instead of "for of". The two objects passed aren't [iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/is_not_iterable) because of the nature of objects and shouldn't be assumed they would be. 

I'm writing a pull request right away.

**Comment by 1000ch** [comment]
@davidwebca @paulmist @hunterruth 
Could you tell me which version of Node.js do you use?

**Comment by 1000ch** [comment]
I published the patched version of `Sublime-svgo` v2.6.1, could you try to use the newest version?

**Comment by davidwebca** [comment]
There's an error currently because of line 21 where you declare "plugins" for the user plugins whereas there's already a constant declared higher up to store the cumulative results of plugins. Renaming one of the two fixes the new error and we should be good to go!

**Comment by 1000ch** [comment]
Sorry again, could you try using v2.6.2?

**Comment by davidwebca** [comment]
Yess, everything works! 🎉  Thanks a lot!
